apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    environment: production
    app: myapp

spec:
  containers:
    - name: myapp-container
      image: stacksimplify/kubenginx:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
        